# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
   branches:
     include:
       - 202012
   paths:
     exclude:
       - .github
trigger: none

name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

resources:
  repositories:
    - repository: sonic-mgmt
      type: github
      name: sonic-net/sonic-mgmt
      ref: master
      endpoint: sonic-net

stages:
- stage: Pre_test
  variables:
  - group: GIT_SECRETS
  jobs:
  - job: validate_test_cases
    displayName: "Validate Test Cases"
    timeoutInMinutes: 20
    continueOnError: false
    pool: sonic-common
    steps:
    - template: .azure-pipelines/pytest-collect-only.yml
