parameters:
  - name: TOPOLOGY
    type: string
    default: ""

  - name: POLL_INTERVAL
    type: number
    default: 10

  - name: POLL_TIMEOUT
    type: number
    default: 36000

  - name: MIN_WORKER
    type: string
    default: ""

  - name: MAX_WORKER
    type: string
    default: ""

  - name: LOCK_WAIT_TIMEOUT_SECONDS
    type: string
    default: ""

  - name: NUM_ASIC
    type: number
    default: 1

  - name: TEST_SET
    type: string
    default: ""

  - name: DEPLOY_MG_EXTRA_PARAMS
    type: string
    default: ""

  - name: COMMON_EXTRA_PARAMS
    type: string
    default: ""

  - name: VM_TYPE
    type: string
    default: "ceos"

  - name: TESTBED_NAME
    type: string
    default: ""

  - name: IMAGE_URL
    type: string
    default: ""

  - name: UPGRADE_IMAGE_PARAM
    type: string
    default: ""

  - name: HWSKU
    type: string
    default: ""

  - name: TEST_PLAN_TYPE
    type: string
    default: ""

  - name: PLATFORM
    type: string
    default: ""

  - name: SCRIPTS
    type: string
    default: ""

  - name: FEATURES
    type: string
    default: ""

  - name: SCRIPTS_EXCLUDE
    type: string
    default: ""

  - name: FEATURES_EXCLUDE
    type: string
    default: ""

  - name: SPECIFIC_PARAM
    type: string
    default: "[]"

  - name: AFFINITY
    type: string
    default: "[]"

  - name: BUILD_REASON
    type: string
    default: ""

  - name: REPO_NAME
    type: string
    default: ""

  - name: MGMT_BRANCH
    type: string
    default: ""

  - name: MGMT_URL
    type: string
    default: "https://raw.githubusercontent.com/sonic-net/sonic-mgmt"

  - name: STOP_ON_FAILURE
    type: string
    default: ""

  - name: RETRY_TIMES
    type: string
    default: ""

  - name: DUMP_KVM_IF_FAIL
    type: string
    default: "False"  # KVM dump has beed deleted
    values:
      - "True"
      - "False"

  - name: REQUESTER
    type: string
    default: ""

  - name: MAX_RUN_TEST_MINUTES
    type: number
    default: 480

  - name: KVM_IMAGE_BRANCH
    type: string
    default: ""

  - name: EXPECTED_RESULT
    type: string
    default: ""

  - name: TEST_PLAN_NUM
    type: string
    default: ""

steps:
  - script: |
      # Check if azure cli is installed. If not, try to install it
      if ! command -v az; then
        echo "Azure CLI is not installed. Trying to install it..."
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      else
        echo "Azure CLI is already installed"
      fi
    displayName: "Install azure-cli"

  - task: AzureCLI@2
    inputs:
      azureSubscription: "SONiC-Automation"
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        set -ex
        accessToken=$(az account get-access-token --resource "$(ELASTICTEST_MSAL_CLIENT_ID)" --query accessToken -o tsv)
        # Base64 encode the variable
        encoded_value=$(echo -n "$accessToken" | base64)

        # Print the encoded value
        echo "Encoded value: $encoded_value"

    displayName: "test access token"
